version: "2"

services:
  ansible:
    image: elnebuloso/ansible:2.8
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "false"
    volumes:
      - .:/etc/ansible/roles/ansible-role
    working_dir: /etc/ansible/roles/ansible-role

  ansible-lint:
    image: sdesbure/ansible-lint
    volumes:
      - .:/ansible-role
    working_dir: /ansible-role

  ubuntu14:
    image: elnebuloso/sshd:ubuntu14

  ubuntu16:
    image: elnebuloso/sshd:ubuntu16

  ubuntu18:
    image: elnebuloso/sshd:ubuntu18

  ubuntu19:
    image: elnebuloso/sshd:ubuntu19

  ubuntu20:
    image: elnebuloso/sshd:ubuntu20