---
- name: install aptitude
  apt: pkg=aptitude state=present update_cache=yes cache_valid_time=3600
  when: package_upgrade_all != ""

- name: update apt cache for upgrade packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: package_upgrade_all != ""

- name: upgrade packages
  apt:
    upgrade: "{{package_upgrade_all}}"
  when: package_upgrade_all != ""
