name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:
  main:
    name: Release
    runs-on: elnebuloso/ansible:2
    steps:
      - name: Checkout
        uses: actions/checkout@master
#      - name: My first step
#        uses: docker://elnebuloso/ansible:2
#        run: |
#          ansible --version